# Sponsor ou_estimator development
# Uncomment the platforms you use:
github: [rakibulmehedi]
# ko_fi: # Replace with your Ko-fi username
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# custom: ["https://example.com/donate"]
